### ISSUE TITLE
Wyświetlanie utworów

### ISSUE THREAD

**Issue by mateuszchalaba** [mateuszchalaba/Internetowy-ranking-utworow-muzycznych#22]
Wyświetlanie listy utworów na stronie głównej

**Comment by AddaM07** [comment]
Pozostało:
- wystylizowanie listy utworów(.css),
- połączenie widoku z Backend'em poprzez AJAX + ogólnie skrypty do interakcji na zdarzenia(.js),
  -biblioteki i pluginy(.js)

**Comment by AddaM07** [comment]
Wykonano
